version: "3"
services:
  titanic_db:
    container_name: titanic_db
    image: "mysql:8"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=titanic_db
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
    volumes:
      - "./dump.sql:/docker-entrypoint-initdb.d/1.sql"
  titanic-flask-app:
    container_name: titanic-flask-app
    image: titanic-flask-app
    build: .
    ports:
      - 5000:5000
    depends_on:
      titanic_db:
        condition: service_healthy
